// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// app/layout.tsx
// src/app/layout.tsx
// src/app/layout.tsx
import './globals.css'; // Import global styles
import { ReactNode } from 'react';
import Link from 'next/link';  // Import Next.js Link component

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 min-h-screen flex flex-col">
        {/* Header */}
        <header className="bg-blue-600 text-white p-4">
          <nav className="container mx-auto">
            <h1 className="text-xl font-bold">Distributed URL Shortener</h1>
          </nav>
        </header>

        {/* Main content */}
        <main className="container mx-auto flex-grow py-8">
          {children}
        </main>

        {/* Footer with navigation */}
        <footer className="bg-gray-200 p-4">
          <nav className="container mx-auto flex justify-around">
            <Link href="/" passHref>
              <button className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700">
                Home
              </button>
            </Link>
            <Link href="/retrieve" passHref>
              <button className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700">
                Retrieve URL
              </button>
            </Link>
            <Link href="/nodes" passHref>
              <button className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700">
                Node Management
              </button>
            </Link>
            <Link href="/visualize" passHref>
              <button className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700">
                Visualization
              </button>
            </Link>
          </nav>
        </footer>
      </body>
    </html>
  );
}
