apiVersion: v1
kind: Service
metadata:
  name: chord-url-shortening
spec:
  type: LoadBalancer
  selector:
    app: chord-url-shortening
  sessionAffinity: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 50051
    targetPort: 50051